name: 'Create PDF for web page'
description: 'A Github action that creates PDF for web page.'
branding:
  icon: file-text
  color: red
inputs:
  address:
    description: 'Webpage address to generate PDF from.'
    required: true
  output:
    description: 'Output directory. Right now it has to exist.'
    required: true
  file-name:
    description: 'Output file name.'
    required: true
  append-metadata:
    description: 'Append timestamp to file name.'
    required: false
    default: false
  commit:
    description: 'Commit hash.'
    required: false
  script-path:
    description: 'Path to javascript script to be run on the web page before the pdf is created.'
    required: false
  css-path:
    description: 'Path to css styles file to be run on the web page before the pdf is created.'
    required: false
  media-type:
    description: 'Emulate media type. Possible types: None/Screen/Print.'
    required: false
    default: 'None'
  paper-format:
    description: 'Paper format.'
    required: false
outputs:
  title:
    description: 'The title of the action.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '-a'
  - ${{ inputs.address }}
  - '-o'
  - ${{ inputs.output }}
  - '-f'
  - ${{ inputs.file-name }}
  - '-m'
  - ${{ inputs.append-metadata }}
  - '-c'
  - ${{ inputs.commit }}
  - '-s'
  - ${{ inputs.script-path }}
  - '--css'
  - ${{ inputs.css-path }}
  - '-t'
  - ${{ inputs.media-type }}
  - '--format'
  - ${{ inputs.paper-forma }}